# Generated by Django 5.2.16 on 2026-08-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('general', 'General AI'), ('document', 'Document AI')], default='general', max_length=20),
        ),
    ]
